### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by jeffryhartanto** [CS2103JAN2017-W09-B1/main#83]
# Contact Us
- You have to change the content of this page accordingly.

# About Us
- Put people other than 4 of you into Contributors section.

# User Guide
- Add links to the commands mentioned before Introduction.
- You can cropped the image for the download instruction, since it shows v0.2 which might be a bit misleading.
- Most links do not work, please check.
- Problems with 3.13, 3.14 and 3.16.
- In general, it's not so well-formatted. 
- See if you can make the command format easier to type.
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

# Developer Guide
- Most links do not work.. TOC has many duplicates..
- `addressbook` is still mentioned in the text.
- Most of the reasons stated in the user stories is not good, especially for `add`.
- For some use cases how come the system can start the interaction? Most of your MSS's are good since it captures back-and-forth interaction between user and the system.
- Diagrams haven't been updated.
- Suggested additions:
  - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
  -Similarly, you can explain other interesting design decisions you made.

Overall, I think your v0.3 has most of the must-have-features required for this project. However, I think the appendices are not so good.

**Comment by geraldwong** [comment]
About Us page already has contributors.

**Comment by jeffryhartanto** [comment]
@geraldwong Prof. Damith and other people that you listed in the `Project Team` are not your teammates. You should mention them in the Contributors section, if you want.

**Comment by bqnguyen94** [comment]
Updated UserGuide.md

**Comment by bqnguyen94** [comment]
Updated DeveloperGuide.md

**Comment by bqnguyen94** [comment]
Updated ContactUs.md and AboutUs.md
